### PR TITLE
DXE-2409 Update cli-diagnostics version to v1.1.0

### PR DESCRIPTION
**Pull request by zenkars**

### CODE REVIEW

**Comment by lkowalsk-akamai-com** [comment]
@zenkars was the 1.1.0 ever released? I see that there is the branch, but not the release: https://github.com/akamai/cli-diagnostics/releases/tag/v1.0.0

**Comment by zenkars** [comment]
Hi Lukasz,
the release is under ‘pre-release’ tag, I was waiting for this PR to be merged.

From: Lukasz Kowalski ***@***.***>
Reply-To: akamai/cli ***@***.***>
Date: Tuesday, March 7, 2023 at 5:46 PM
To: akamai/cli ***@***.***>
Cc: "Srinivas, Zenkar" ***@***.***>, Mention ***@***.***>
Subject: Re: [akamai/cli] Update cli-diagnostics version to v1.1.0 (PR #164)


@zenkars<https://urldefense.com/v3/__https:/github.com/zenkars__;!!GjvTz_vk!SXFvleXa4BS0g_F_5mpMkEhKWtW84UJ9wzLLtKFjp0CguV3OjT5O4f62PbE-GvFBnw-uHxa0DQcYBm60HUWv6BM$> was the 1.1.0 ever released? I see that there is the branch, but not the release: https://github.com/akamai/cli-diagnostics/releases/tag/v1.0.0<https://urldefense.com/v3/__https:/github.com/akamai/cli-diagnostics/releases/tag/v1.0.0__;!!GjvTz_vk!SXFvleXa4BS0g_F_5mpMkEhKWtW84UJ9wzLLtKFjp0CguV3OjT5O4f62PbE-GvFBnw-uHxa0DQcYBm60EYZEqcM$>

**Comment by zenkars** [comment]
Release 1.1.0 https://github.com/akamai/cli-diagnostics/releases/tag/v1.1.0

**Comment by lkowalsk-akamai-com** [comment]
@zenkars  unless you prove me wrong, I think you first should do the release, then we can take it upstream. We are planning a release of CLI next week, so it would make sense to include this change.

**Comment by zenkars** [comment]
> @zenkars unless you prove me wrong, I think you first should do the release, then we can take it upstream. We are planning a release of CLI next week, so it would make sense to include this change.

**Comment by zenkars** [comment]
@lkowalsk-akamai-com , I've updated the latest release to v1.1.0

**Review by lkowalsk-akamai-com — APPROVED** [review]

**Comment by lkowalsk-akamai-com** [comment]
@zenkars ok, thanks. We will merge it soon and include in next weeks release.

**Pull request merged**
