### PR TITLE
Adds community created extensions

### PR DESCRIPTION
**Pull request by RafPe**
Adds links to community created extensions 
* https://github.com/partamonov/akamai-cli-siteshield
* https://github.com/partamonov/akamai-cli-netstorage

Maybe it would be good idea to add repository for plugins so people could merge when created ? 

Thanks 
R

### CODE REVIEW

**Comment by partamonov** [comment]
This one as well can be added:
* https://github.com/partamonov/akamai-cli-frn

**Comment by RafPe** [comment]
I have added the repo URL into the readme

**Comment by RafPe** [comment]
Added new plugin for network management .... cool if anyone would be around to merge it ?!

**Comment by dshafik** [comment]
@rafpe we are currently trying to launch the CLI website and are figuring out the best way to showcase third party contributions.

I'll see if we can merge this in this week however as we are very excited to see what you're working on!

**Comment by RafPe** [comment]
@dshafik We would be more than happy to contribute more as we have many use case scenarios for such automation tooling

**Comment by dshafik** [comment]
@RafPe can you reach out to me via email, dshafik@akamai.com — I'd love to discuss your involvement further! :)

**Comment by rajiv** [comment]
@dshafik how about enabling the wiki on this project in github. then the community can manage the list on our own, outside of the main codebase.

**Comment by robertolopezlopez** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
